services:
  - type: web
    name: linkedin-bot
    env: node
    buildCommand: npm install
    startCommand: node telegram_bot.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false